# CircleCI config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12-stretch
    working_directory: ~/challenge-bypass-extension
    steps:
      - run: sudo apt update
      - run: sudo apt install default-jre build-essential
      - checkout
      - run: git submodule update --init
      - run: make install
      - run: make lint
      - run: make build
      - run: make test
