# CircleCI config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12-stretch
    working_directory: ~/challenge-bypass-extension
    steps:
      - checkout
      - run:
          name: Fetching Sources
          command: make install
      - run:
          name: Linting
          command: make lint
      - run:
          name: Building
          command: make build
      - run:
          name: Testing
          command: make test-all
